// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using YSI.CurseOfSilverCrown.Web.Data;

namespace YSI.CurseOfSilverCrown.Web.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.4")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens");
                });

            modelBuilder.Entity("YSI.CurseOfSilverCrown.Core.Database.Models.Command", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Coffers")
                        .HasColumnType("int");

                    b.Property<string>("OrganizationId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("TargetOrganizationId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<int>("Warriors")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("OrganizationId");

                    b.HasIndex("TargetOrganizationId");

                    b.HasIndex("Type");

                    b.ToTable("Commands");
                });

            modelBuilder.Entity("YSI.CurseOfSilverCrown.Core.Database.Models.EventStory", b =>
                {
                    b.Property<int>("TurnId")
                        .HasColumnType("int");

                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("EventStoryJson")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TurnId", "Id");

                    b.ToTable("EventStories");
                });

            modelBuilder.Entity("YSI.CurseOfSilverCrown.Core.Database.Models.Organization", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Coffers")
                        .HasColumnType("int");

                    b.Property<int>("Investments")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("OrganizationType")
                        .HasColumnType("int");

                    b.Property<int>("ProvinceId")
                        .HasColumnType("int");

                    b.Property<string>("SuzerainId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Warriors")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("OrganizationType");

                    b.HasIndex("ProvinceId");

                    b.HasIndex("SuzerainId");

                    b.ToTable("Organizations");

                    b.HasData(
                        new
                        {
                            Id = "TinMines",
                            Coffers = 4000,
                            Investments = 0,
                            Name = "Оловянные шахты",
                            OrganizationType = 1,
                            ProvinceId = 1,
                            Warriors = 100
                        },
                        new
                        {
                            Id = "CapeRaptor",
                            Coffers = 4000,
                            Investments = 0,
                            Name = "Мыс ящера",
                            OrganizationType = 1,
                            ProvinceId = 2,
                            Warriors = 100
                        },
                        new
                        {
                            Id = "MouthOfPolaima",
                            Coffers = 4000,
                            Investments = 0,
                            Name = "Устье Полаймы",
                            OrganizationType = 1,
                            ProvinceId = 3,
                            Warriors = 100
                        },
                        new
                        {
                            Id = "HeatherOfDimmoria",
                            Coffers = 4000,
                            Investments = 0,
                            Name = "Верещатник Диммории",
                            OrganizationType = 1,
                            ProvinceId = 4,
                            Warriors = 100
                        },
                        new
                        {
                            Id = "DimmoriaValley",
                            Coffers = 4000,
                            Investments = 0,
                            Name = "Долина Диммории",
                            OrganizationType = 1,
                            ProvinceId = 5,
                            Warriors = 100
                        },
                        new
                        {
                            Id = "SummerCoast",
                            Coffers = 4000,
                            Investments = 0,
                            Name = "Летний берег",
                            OrganizationType = 1,
                            ProvinceId = 6,
                            Warriors = 100
                        },
                        new
                        {
                            Id = "DimmoriaFarms",
                            Coffers = 4000,
                            Investments = 0,
                            Name = "Фермы Диммории",
                            OrganizationType = 1,
                            ProvinceId = 7,
                            Warriors = 100
                        },
                        new
                        {
                            Id = "ChalRocks",
                            Coffers = 4000,
                            Investments = 0,
                            Name = "Меловые скалы",
                            OrganizationType = 1,
                            ProvinceId = 8,
                            Warriors = 100
                        },
                        new
                        {
                            Id = "LimestoneRidges",
                            Coffers = 4000,
                            Investments = 0,
                            Name = "Известняковые хребты",
                            OrganizationType = 1,
                            ProvinceId = 9,
                            Warriors = 100
                        });
                });

            modelBuilder.Entity("YSI.CurseOfSilverCrown.Core.Database.Models.OrganizationEventStory", b =>
                {
                    b.Property<int>("TurnId")
                        .HasColumnType("int");

                    b.Property<string>("OrganizationId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("EventStoryId")
                        .HasColumnType("int");

                    b.Property<int>("Importance")
                        .HasColumnType("int");

                    b.HasKey("TurnId", "OrganizationId", "EventStoryId");

                    b.HasIndex("OrganizationId");

                    b.HasIndex("TurnId", "EventStoryId");

                    b.ToTable("OrganizationEventStories");
                });

            modelBuilder.Entity("YSI.CurseOfSilverCrown.Core.Database.Models.Province", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Provinces");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Оловянные шахты"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Мыс ящера"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Устье Полаймы"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Верещатник Диммории"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Долина Диммории"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Летний берег"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Фермы Диммории"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Меловые скалы"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Известняковые хребты"
                        });
                });

            modelBuilder.Entity("YSI.CurseOfSilverCrown.Core.Database.Models.Route", b =>
                {
                    b.Property<int>("FromProvinceId")
                        .HasColumnType("int");

                    b.Property<int>("ToProvinceId")
                        .HasColumnType("int");

                    b.HasKey("FromProvinceId", "ToProvinceId");

                    b.HasIndex("FromProvinceId");

                    b.HasIndex("ToProvinceId");

                    b.ToTable("Routes");

                    b.HasData(
                        new
                        {
                            FromProvinceId = 1,
                            ToProvinceId = 2
                        },
                        new
                        {
                            FromProvinceId = 1,
                            ToProvinceId = 3
                        },
                        new
                        {
                            FromProvinceId = 2,
                            ToProvinceId = 1
                        },
                        new
                        {
                            FromProvinceId = 2,
                            ToProvinceId = 3
                        },
                        new
                        {
                            FromProvinceId = 2,
                            ToProvinceId = 4
                        },
                        new
                        {
                            FromProvinceId = 3,
                            ToProvinceId = 1
                        },
                        new
                        {
                            FromProvinceId = 3,
                            ToProvinceId = 2
                        },
                        new
                        {
                            FromProvinceId = 3,
                            ToProvinceId = 4
                        },
                        new
                        {
                            FromProvinceId = 4,
                            ToProvinceId = 2
                        },
                        new
                        {
                            FromProvinceId = 4,
                            ToProvinceId = 3
                        },
                        new
                        {
                            FromProvinceId = 4,
                            ToProvinceId = 5
                        },
                        new
                        {
                            FromProvinceId = 4,
                            ToProvinceId = 6
                        },
                        new
                        {
                            FromProvinceId = 5,
                            ToProvinceId = 4
                        },
                        new
                        {
                            FromProvinceId = 5,
                            ToProvinceId = 6
                        },
                        new
                        {
                            FromProvinceId = 5,
                            ToProvinceId = 7
                        },
                        new
                        {
                            FromProvinceId = 5,
                            ToProvinceId = 8
                        },
                        new
                        {
                            FromProvinceId = 6,
                            ToProvinceId = 4
                        },
                        new
                        {
                            FromProvinceId = 6,
                            ToProvinceId = 5
                        },
                        new
                        {
                            FromProvinceId = 6,
                            ToProvinceId = 7
                        },
                        new
                        {
                            FromProvinceId = 7,
                            ToProvinceId = 5
                        },
                        new
                        {
                            FromProvinceId = 7,
                            ToProvinceId = 6
                        },
                        new
                        {
                            FromProvinceId = 7,
                            ToProvinceId = 8
                        },
                        new
                        {
                            FromProvinceId = 7,
                            ToProvinceId = 9
                        },
                        new
                        {
                            FromProvinceId = 8,
                            ToProvinceId = 5
                        },
                        new
                        {
                            FromProvinceId = 8,
                            ToProvinceId = 7
                        },
                        new
                        {
                            FromProvinceId = 8,
                            ToProvinceId = 9
                        },
                        new
                        {
                            FromProvinceId = 9,
                            ToProvinceId = 7
                        },
                        new
                        {
                            FromProvinceId = 9,
                            ToProvinceId = 8
                        });
                });

            modelBuilder.Entity("YSI.CurseOfSilverCrown.Core.Database.Models.Turn", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime>("Started")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Turns");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IsActive = true,
                            Started = new DateTime(2021, 4, 30, 4, 27, 42, 268, DateTimeKind.Utc).AddTicks(1403)
                        });
                });

            modelBuilder.Entity("YSI.CurseOfSilverCrown.Core.Database.Models.User", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<DateTime>("LastActivityTime")
                        .HasColumnType("datetime2");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("OrganizationId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.HasIndex("OrganizationId")
                        .IsUnique()
                        .HasFilter("[OrganizationId] IS NOT NULL");

                    b.ToTable("AspNetUsers");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("YSI.CurseOfSilverCrown.Core.Database.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("YSI.CurseOfSilverCrown.Core.Database.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("YSI.CurseOfSilverCrown.Core.Database.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("YSI.CurseOfSilverCrown.Core.Database.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("YSI.CurseOfSilverCrown.Core.Database.Models.Command", b =>
                {
                    b.HasOne("YSI.CurseOfSilverCrown.Core.Database.Models.Organization", "Organization")
                        .WithMany("Commands")
                        .HasForeignKey("OrganizationId");

                    b.HasOne("YSI.CurseOfSilverCrown.Core.Database.Models.Organization", "Target")
                        .WithMany("ToOrganizationCommands")
                        .HasForeignKey("TargetOrganizationId");

                    b.Navigation("Organization");

                    b.Navigation("Target");
                });

            modelBuilder.Entity("YSI.CurseOfSilverCrown.Core.Database.Models.EventStory", b =>
                {
                    b.HasOne("YSI.CurseOfSilverCrown.Core.Database.Models.Turn", "Turn")
                        .WithMany("EventStories")
                        .HasForeignKey("TurnId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Turn");
                });

            modelBuilder.Entity("YSI.CurseOfSilverCrown.Core.Database.Models.Organization", b =>
                {
                    b.HasOne("YSI.CurseOfSilverCrown.Core.Database.Models.Province", "Province")
                        .WithMany("Organizations")
                        .HasForeignKey("ProvinceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("YSI.CurseOfSilverCrown.Core.Database.Models.Organization", "Suzerain")
                        .WithMany("Vassals")
                        .HasForeignKey("SuzerainId");

                    b.Navigation("Province");

                    b.Navigation("Suzerain");
                });

            modelBuilder.Entity("YSI.CurseOfSilverCrown.Core.Database.Models.OrganizationEventStory", b =>
                {
                    b.HasOne("YSI.CurseOfSilverCrown.Core.Database.Models.Organization", "Organization")
                        .WithMany("OrganizationEventStories")
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("YSI.CurseOfSilverCrown.Core.Database.Models.Turn", "Turn")
                        .WithMany("OrganizationEventStories")
                        .HasForeignKey("TurnId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("YSI.CurseOfSilverCrown.Core.Database.Models.EventStory", "EventStory")
                        .WithMany("OrganizationEventStories")
                        .HasForeignKey("TurnId", "EventStoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EventStory");

                    b.Navigation("Organization");

                    b.Navigation("Turn");
                });

            modelBuilder.Entity("YSI.CurseOfSilverCrown.Core.Database.Models.Route", b =>
                {
                    b.HasOne("YSI.CurseOfSilverCrown.Core.Database.Models.Province", "FromProvince")
                        .WithMany("RouteFromHere")
                        .HasForeignKey("FromProvinceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("YSI.CurseOfSilverCrown.Core.Database.Models.Province", "ToProvince")
                        .WithMany("RouteToHere")
                        .HasForeignKey("ToProvinceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("FromProvince");

                    b.Navigation("ToProvince");
                });

            modelBuilder.Entity("YSI.CurseOfSilverCrown.Core.Database.Models.User", b =>
                {
                    b.HasOne("YSI.CurseOfSilverCrown.Core.Database.Models.Organization", "Organization")
                        .WithOne("User")
                        .HasForeignKey("YSI.CurseOfSilverCrown.Core.Database.Models.User", "OrganizationId");

                    b.Navigation("Organization");
                });

            modelBuilder.Entity("YSI.CurseOfSilverCrown.Core.Database.Models.EventStory", b =>
                {
                    b.Navigation("OrganizationEventStories");
                });

            modelBuilder.Entity("YSI.CurseOfSilverCrown.Core.Database.Models.Organization", b =>
                {
                    b.Navigation("Commands");

                    b.Navigation("OrganizationEventStories");

                    b.Navigation("ToOrganizationCommands");

                    b.Navigation("User");

                    b.Navigation("Vassals");
                });

            modelBuilder.Entity("YSI.CurseOfSilverCrown.Core.Database.Models.Province", b =>
                {
                    b.Navigation("Organizations");

                    b.Navigation("RouteFromHere");

                    b.Navigation("RouteToHere");
                });

            modelBuilder.Entity("YSI.CurseOfSilverCrown.Core.Database.Models.Turn", b =>
                {
                    b.Navigation("EventStories");

                    b.Navigation("OrganizationEventStories");
                });
#pragma warning restore 612, 618
        }
    }
}
