//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YAGO.World.Infrastructure.Database.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class StoryResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal StoryResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("YAGO.World.Infrastructure.Database.Resources.StoryResources", typeof(StoryResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Шафран, корица, сушеные лимоны&quot;, - бормотал Дари, ступая по выщербленным плитам улиц Истиллы. Густой воздух, пропитанный пеплом и гарью, щекотал ноздри - вечное напоминание о пробудившемся два месяца назад вулкане..
        /// </summary>
        internal static string Slide_00001 {
            get {
                return ResourceManager.GetString("Slide_00001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Но даже сквозь пелену город поражал воображение: бронзовые изваяния героев на перекрестках, стройные колонны храмов, и особенно - уверенные в себе люди в дорогих одеяниях, спорящие на равных с эльнирами..
        /// </summary>
        internal static string Slide_00002 {
            get {
                return ResourceManager.GetString("Slide_00002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ноги сами несли его знакомой дорогой: под сводчатой аркой, мимо величественного храма бога-кузнеца с бронзовым молотом над входом, вниз по склону - туда, где воздух становился густым от ароматов специй и соленой рыбы..
        /// </summary>
        internal static string Slide_00003 {
            get {
                return ResourceManager.GetString("Slide_00003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Верхний город с его эльнирской чопорностью остался позади. Здесь, на рынке, царила совсем иная жизнь - шумная, пахнущая чесноком и тмином, где среди толпы в простых холщовых туниках лишь изредка мелькали остроконечные уши под капюшонами..
        /// </summary>
        internal static string Slide_00004 {
            get {
                return ResourceManager.GetString("Slide_00004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Но сегодня что-то было не так. Привычный рыночный гул сменился тревожным ропотом. У старого дуба на окраине площади столпились люди. На перевернутом бочонке стоял загорелый мужчина в потертом гиматии, он яростно жестикулировал и кричал что-то о &quot;каре небес&quot;..
        /// </summary>
        internal static string Slide_00005 {
            get {
                return ResourceManager.GetString("Slide_00005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Мальчик пробирался между людьми, ловя обрывки фраз: «…драконы и демоны!», «…эльниры разгневали богов!». Сердце Дари учащенно забилось - эти слова касались его господ. Он замер, наблюдая, как люди вокруг перешёптывались, сжимая в потных ладонях деревянные обереги и глиняные амулеты..
        /// </summary>
        internal static string Slide_00006 {
            get {
                return ResourceManager.GetString("Slide_00006", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дари замер, втянув голову в плечи. Голос проповедника, хриплый от крика, резал воздух, будто нож.{0}«Они лгут вам о своей магии!» — мужчина вскинул руки к пепельному небу. «Эльниры принесли с запада не знания — они принесли чуму!»{0}Его слова падали, как раскалённые угли....
        /// </summary>
        internal static string Slide_00007 {
            get {
                return ResourceManager.GetString("Slide_00007", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Когда первые эльнирские корабли причалили к нашим берегам, они уже были отравлены. Отравлены договором с теми, кто живёт за гранью миров. С демонами.&quot;.
        /// </summary>
        internal static string Slide_00008 {
            get {
                return ResourceManager.GetString("Slide_00008", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;За преданные души они получили три дара: ложную магию, что искривляет наш мир; демонов-стражей — огромных, с рогами и горящими глазами, что бродят по их дворцам; и драконов — не животных, а орудия разрушения, выкованные в самых тёмных безднах.&quot;.
        /// </summary>
        internal static string Slide_00009 {
            get {
                return ResourceManager.GetString("Slide_00009", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Но боги не слепы! Разве вы не видите? Жемчужная Гавань пала не случайно — она была стёрта с лица земли за их грехи. Вулкан — это не бедствие, а очищение! И пока последний эльнир стоит на нашей земле, кара будет продолжаться!&quot;.
        /// </summary>
        internal static string Slide_00010 {
            get {
                return ResourceManager.GetString("Slide_00010", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Толпа загудела. Дари отступил на шаг, чувствуя, как ладони становятся влажными. Он — слуга эльнирского чародея. Он видел странные ритуалы, слышал непонятные слова...{0}Но правда ли это?.
        /// </summary>
        internal static string Slide_00011 {
            get {
                return ResourceManager.GetString("Slide_00011", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дари наконец выбрался из гущи толпы, оставив за спиной крики проповедника и возбуждённый гул. Перед ним снова раскинулся шумный рынок, где воздух был густ от ароматов жареного лука и душистого тмина..
        /// </summary>
        internal static string Slide_00012 {
            get {
                return ResourceManager.GetString("Slide_00012", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Прилавок старого Харуфа узнавался сразу: медные чаши с яркими порошками, связки сушёных трав, а сам торговец - толстый, с седыми бровями-кустами - уже махал ему ложкой, поднимая облачко пряной пыли..
        /// </summary>
        internal static string Slide_00013 {
            get {
                return ResourceManager.GetString("Slide_00013", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to — На этом всё.{0}Харуф фыркнул, упаковывая свёртки в грубую бумагу. Его пальцы ловко затягивали бечёвку, закручивая её в тугой узел.{0}— Вот так набор! — Подмигнул, встряхивая свёртки. — Настоящее противопепельное зелье!.
        /// </summary>
        internal static string Slide_00014 {
            get {
                return ResourceManager.GetString("Slide_00014", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Мальчик уже отошёл на добрых двадцать шагов, когда сбоку раздался зазывный свист:{0}— Эй, золотце! Подойди-ка сюда!{0}У лотка, усыпанного финиками в меду и леденцами в форме морских звёзд, стоял веснушчатый парень..
        /// </summary>
        internal static string Slide_00015 {
            get {
                return ResourceManager.GetString("Slide_00015", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Его рыжие брови поползли вверх, когда он разглядел на старом потрёпанном хитоне Дари вышитые по подолу раковины — знак эльнирской знати Жемчужной Гавани.{0}— Вижу, важным господам служишь, — протянул он кусочек лукума, липкий от розовой патоки. — Бери, не стесняйся. Сегодня угощаю..
        /// </summary>
        internal static string Slide_00016 {
            get {
                return ResourceManager.GetString("Slide_00016", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to — Спасибо, — Дари принял угощение. Розовая патока таяла на языке, оставляя вкус мёда и миндаля.{0}— Видишь, дружок, — торговец наклонился, сладкий дымок фиников окутал его, — я человек простой, но понимаю: слуга слугой, а свой живот тоже хочет праздника..
        /// </summary>
        internal static string Slide_00017 {
            get {
                return ResourceManager.GetString("Slide_00017", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to — Благодарю, но не смею, — Дари спрятал руки за спину. Ключница Марда строго-настрого запрещала брать угощения с рынка.{0}— Ой, неужто боишься? — торговец засмеялся. — Другие слуги в твои годы уже монетки копят..
        /// </summary>
        internal static string Slide_00018 {
            get {
                return ResourceManager.GetString("Slide_00018", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дари отпрянул, судорожно прижав свёртки со специями к груди. Торговец сладостей замер с кусочком лукума в протянутой руке.{0}— Эй, не пугайся! — продавец оглянулся по сторонам, приглушив голос. — Я ж не демон эльнирский, малец. Просто хотел угостить....
        /// </summary>
        internal static string Slide_00019 {
            get {
                return ResourceManager.GetString("Slide_00019", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дари лишь мельком взглянул на протянутую руку и, не замедляя шага, увернулся в сторону. Торговец замер с угощением в воздухе, пока мальчик ловко нырял между возами с товарами, растворяясь в рыночной суете..
        /// </summary>
        internal static string Slide_00020 {
            get {
                return ResourceManager.GetString("Slide_00020", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дари закусил губу, окинув торговца оценивающим взглядом. {0}— Хорошо... я что-нибудь принесу, — наконец пробормотал он, делая вид, что осматривает товары..
        /// </summary>
        internal static string Slide_00021 {
            get {
                return ResourceManager.GetString("Slide_00021", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дари нахмурился, крепче сжимая свёртки со специями. Он был честным слугой дома Илтаринов - мысль взять что-то у господ казалась ему немыслимой.{0}— Я не буду воровать! — сказал он твёрже, чем ожидал сам..
        /// </summary>
        internal static string Slide_00022 {
            get {
                return ResourceManager.GetString("Slide_00022", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to — Я... пожалуй пойду, — пробормотал Дари и, не дожидаясь ответа, рванул вперёд.{0}— Эх! — Торговец лишь щёлкнул языком. — Заходи, если надумаешь. Я здесь до заката....
        /// </summary>
        internal static string Slide_00023 {
            get {
                return ResourceManager.GetString("Slide_00023", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to У ворот Верхнего города стражник-эльнир лениво кивнул Дари — мальчика, ежедневно бегающего с поручениями, здесь знали в лицо. Улицы встретили его вечерней прохладой. Тень грифона скользнула по мостовой — где-то высоко эльнирский всадник патрулировал город..
        /// </summary>
        internal static string Slide_00024 {
            get {
                return ResourceManager.GetString("Slide_00024", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Свёртки в руках благоухали смесью специй, перебивая пепельный запах. Поручение выполнено, и теперь оставалось лишь надеяться, что он ничего не перепутал в рыночной суете..
        /// </summary>
        internal static string Slide_00025 {
            get {
                return ResourceManager.GetString("Slide_00025", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дари молча протянул серебряные монеты — те самые, что ему вручила ключница. Торговец щёлкнул языком, отсчитывая сдачу медяками.{0}— Удачного дня, — буркнул Харуф.{0}Дари прижал свёртки к груди, ощущая сквозь бумагу терпкий аромат специй, и зашагал прочь, стуча медяками в кулаке..
        /// </summary>
        internal static string Slide_00026 {
            get {
                return ResourceManager.GetString("Slide_00026", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Голос торговца стал шепотом, глаза весело подмигнули:{0}— Если вдруг... случайно найдёшь у господ что-то ненужное — приноси мне. За безделушку — сладости каждый день, за серьёзную вещицу — серебро. Ну как?.
        /// </summary>
        internal static string Slide_00027 {
            get {
                return ResourceManager.GetString("Slide_00027", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дари провёл языком по пересохшим губам. В груди теснилось странное чувство - будто он стоит на краю чего-то важного. &quot;Сначала специи, - мысленно вздохнул он, - а там... видно будет&quot;. Отстраняясь от толпы, он решительно двинулся прочь..
        /// </summary>
        internal static string Slide_00028 {
            get {
                return ResourceManager.GetString("Slide_00028", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to В голове всплыли рассказы Лиры: до эльниров люди не знали ни театров, ни законов, ни даже письменности. А теперь — библиотеки, лекарства, чеканные монеты... Дари вздохнул, глядя, как старый рыбак целует амулет. &quot;Если бы они видели, как господин Илатрин лечит детей травами...&quot;.
        /// </summary>
        internal static string Slide_00029 {
            get {
                return ResourceManager.GetString("Slide_00029", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Неужели я служу демонам?&quot; — ледяная дрожь пробежала по спине. &quot;Почему драконы подчиняются эльнирам?&quot; Пальцы сами потянулись к амулету Лиры, но дёрнулись прочь, будто коснулись раскалённого металла..
        /// </summary>
        internal static string Slide_00030 {
            get {
                return ResourceManager.GetString("Slide_00030", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дари закусил губу. Слова проповедника расходились с тем, чему учили в доме эльниров. &quot;Хозяева вряд ли стали бы признаваться, если служат демонам...&quot; — мелькнуло у него.
        ///Он переступил с ноги на ногу. Где правда ещё предстоит разобраться..
        /// </summary>
        internal static string Slide_00031 {
            get {
                return ResourceManager.GetString("Slide_00031", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to — Куркуму... — пробормотал Дари, разглядывая жёлтый порошок.{0}Харуф фыркнул, черпая дешёвую специю деревянной ложкой:{0}— Двадцать медяков за горсть. Но предупреждаю — шафраном это не пахнет, хоть и цветом похоже..
        /// </summary>
        internal static string Slide_00032 {
            get {
                return ResourceManager.GetString("Slide_00032", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to — Шафран, — кивнул Дари, указывая на алые нити.{0}Харуф бережно подцепил щепотку:{0}— Два серебряника за унцию. Осторожнее — одна щепоть на котёл, а то разоришь своих господ..
        /// </summary>
        internal static string Slide_00033 {
            get {
                return ResourceManager.GetString("Slide_00033", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to — Кар-да-мон? — растянул Дари, будто пробуя слово.{0}Харуф свистнул, доставая резной ларец:{0}— Полтора серебряника за горсть. Твои эльниры, видать, небось ритуал затеяли?.
        /// </summary>
        internal static string Slide_00034 {
            get {
                return ResourceManager.GetString("Slide_00034", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to — Сушёные апельсины... — неуверенно сказал Дари.{0}Харуф почесал бороду:{0}— Десять медяков. Для мяса сойдёт, но рыбу испортишь. Твой повар в прошлый раз плевался..
        /// </summary>
        internal static string Slide_00035 {
            get {
                return ResourceManager.GetString("Slide_00035", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to — Сушёные лимоны, — вспомнил Дари кислый вкус.{0}Харуф швырнул в свёрток горсть долек:{0}— Пятнадцать медяков. Если господам не впервой кислятину жевать..
        /// </summary>
        internal static string Slide_00036 {
            get {
                return ResourceManager.GetString("Slide_00036", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to — Корицу, — ткнул Дари в палочки.{0}Харуф ловко отмерил связку:{0}— Пятьдесят медяков. Главное — не перепутай с кассией, а то ключница Марда носом покрутит..
        /// </summary>
        internal static string Slide_00037 {
            get {
                return ResourceManager.GetString("Slide_00037", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дари помнил этого человека ещё по Жемчужной Гавани. Тот торговал специями у Старого причала, пока вулкан не стёр их город с лица земли. Теперь здесь, в Истилле, его лавка ютилась между палатками беженцев, а вместо морского бриза в воздухе висел пепел..
        /// </summary>
        internal static string Slide_00038 {
            get {
                return ResourceManager.GetString("Slide_00038", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to — Опять за специями, птенчик? — Харуф щёлкнул языком, вытирая руки о запачканный передник. — Марда всё ещё не верит, что здешний шафран — жалкая подделка? Настоящий-то рос у нас на острове, в горах... Ладно, нечего разнюниваться. Выбирай быстрее — народ подходит!.
        /// </summary>
        internal static string Slide_00039 {
            get {
                return ResourceManager.GetString("Slide_00039", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Тот день начался с гула под ногами и чёрной тучи над морем. К полудню наступила тьма, а к вечеру гигантские волны от извержения на соседнем острове смели пристани Жемчужной Гавани..
        /// </summary>
        internal static string Slide_00040 {
            get {
                return ResourceManager.GetString("Slide_00040", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Первые три дня солнца не было вовсе — только пепел, оседающий на ресницах и губах. К десятому дню сквозь рыжую мглу проглядывало багровое пятно, но ещё месяц небо хмурилось серой пеленой..
        /// </summary>
        internal static string Slide_00041 {
            get {
                return ResourceManager.GetString("Slide_00041", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Квартал, где жил Дари, на холмах уцелел, но нижний город превратился в груду балок и камней. Юноша бегал с вестями через разрушенные кварталы, где воздух обжигал лёгкие, а люди заворачивали мёртвых в пропитанные пеплом плащи..
        /// </summary>
        internal static string Slide_00042 {
            get {
                return ResourceManager.GetString("Slide_00042", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Когда через двадцать дней корабль отплывал, над островом всё ещё висела мгла. В Истилле волны докатились ослабленными, но всё же разрушили портовые постройки. Даже через месяц после прибытия небо здесь оставалось медным, а воздух — горьким от гари..
        /// </summary>
        internal static string Slide_00043 {
            get {
                return ResourceManager.GetString("Slide_00043", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to — Отлично! — Торговец хлопнул в ладоши, брызги патоки осели на прилавке. — Запомни, птенчик: чем больше блестит — тем слаще награда. — Он подмигнул, обнажая золотой зуб. — Я здесь каждый день до заката..
        /// </summary>
        internal static string Slide_00044 {
            get {
                return ResourceManager.GetString("Slide_00044", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to — Ох уж эти благородные слуги! — Торговец фыркнул, вытирая липкие пальцы о фартук. — Кто ж говорит о воровстве? Я про вещи, что пылятся без дела... — Он махнул рукой. — Ладно, ступай..
        /// </summary>
        internal static string Slide_00045 {
            get {
                return ResourceManager.GetString("Slide_00045", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Но Лира... она же добрая&quot;, — слабо возразил себе Дари. Перед глазами всплыло, как они вместе смеялись, когда её пальцы заставили стеклянный шар светиться ровным белым светом. &quot;Смотри, Дари! У меня получилось!&quot; — сияла она тогда. — &quot;Может, она и сама не понимает, что её магия... от демонов?&quot;.
        /// </summary>
        internal static string Slide_00046 {
            get {
                return ResourceManager.GetString("Slide_00046", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Каждый день в Истиллу прибывали новые беженцы. Сначала горожане помогали — делились хлебом, пускали ночевать под портиками. Но когда цены на зерно взлетели, а улицы заполонили чужаки, в глазах местных засветилось раздражение..
        /// </summary>
        internal static string Slide_00047 {
            get {
                return ResourceManager.GetString("Slide_00047", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Островитяне ютились у городских стен, продавая последнее: потрёпанные пеплосы, бронзовые амулеты, гвозди с разбитых кораблей. У фонтанов вспыхивали драки за воду, у пекарен — за хлебные корки. Возле гавани, среди перевёрнутых лодок и пустых амфор, жили те, кому не нашлось места даже в трущобах..
        /// </summary>
        internal static string Slide_00048 {
            get {
                return ResourceManager.GetString("Slide_00048", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Новые беженцы прибывали измождёнными, с пустыми руками. Их уже не встречали, как первых, мисками тёплой похлёбки. Вместо хлеба им доставались лишь косые взгляды да брань. Но куда им было деться? За спиной — лишь пепел родных островов да бескрайнее море..
        /// </summary>
        internal static string Slide_00049 {
            get {
                return ResourceManager.GetString("Slide_00049", resourceCulture);
            }
        }
    }
}
