services:

  database:
    image: postgres:18
    volumes:
      - a04d029fa594e5f95dd24afa9b98eca2d771f30949fc577da3c5ccfeb61372e0:/var/lib/postgresql/
    environment:
      POSTGRES_DB: yagoworld_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      PGDATA: /var/lib/postgresql/18/docker
    ports:
      - "127.0.0.1:5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d yagoworld_db"]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 10s
      
  webserver:
    image: webserver
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ConnectionStrings__DefaultConnection=Host=database;Port=5432;Database=yagoworld_db;Username=user;Password=password
      - ASPNETCORE_URLS=https://+:443;http://+:80
    ports:
      - "80:80"
      - "443:443"
    restart: unless-stopped
    depends_on:
      database:
        condition: service_healthy
      
volumes:
  a04d029fa594e5f95dd24afa9b98eca2d771f30949fc577da3c5ccfeb61372e0:
    name: a04d029fa594e5f95dd24afa9b98eca2d771f30949fc577da3c5ccfeb61372e0
    external: true