services:

  database:
    image: postgres:latest
    environment:
      POSTGRES_DB: yagoworld
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
      
  webserver:
    image: webserver
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - database