services:

  database:
    image: postgres:latest
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: yagoworld_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "127.0.0.1:5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d yagoworld_db"]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 10s
      
  webserver:
    image: webserver
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=database;Port=5432;Database=yagoworld_db;Username=user;Password=password
      - ASPNETCORE_URLS=http://+:80
    ports:
      - "80:80"
      - "443:443"
    restart: unless-stopped
    depends_on:
      database:
        condition: service_healthy
      
volumes:
  postgres_data: